# Generated by Django 4.0.6 on 2022-08-13 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='activit',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='krk',
        ),
        migrations.AddField(
            model_name='variation',
            name='activite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client.activite'),
        ),
    ]
