# Generated by Django 4.0.6 on 2022-08-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_rename_nombre_operation_quantite_operation_tarif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='activites',
        ),
        migrations.AddField(
            model_name='operation',
            name='activites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Client.activite'),
        ),
    ]
