# Generated by Django 4.0.6 on 2022-08-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_remove_operation_activites_operation_activites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='lien',
        ),
    ]
