# Generated by Django 4.0.6 on 2022-08-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_remove_client_lien'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='activites',
            new_name='activite',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='clients',
            new_name='client',
        ),
    ]
