# Generated by Django 4.0.6 on 2022-08-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_alter_abonnement_debut_alter_abonnement_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='dateDePayement',
            field=models.DateField(null=True),
        ),
    ]
